spring:
  profiles:
    active: heroku
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
        ddl-auto: update
        naming:
          implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    #https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot
    open-in-view: false
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        session_factory:
          interceptor: com.itsight.cuy.interceptor.EntityInterceptorImpl
        jdbc:
          batch_size: 400
          batch_versioned_data: true
 # Templates reloading during development
  thymeleaf:
    cache: false
    encoding: UTF-8
    suffix: .html
    prefix: file:src/main/resources/templates/
# Static resources reloading during development
  resources:
    static-locations: file:src/main/resources/static/
  servlet:
    multipart:
      max-request-size: 16MB
      max-file-size: 8MB
    
